apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask
      image: flask-api
      ports:
        - containerPort: 5000
      securityContext:
        runAsNonRoot: true
